# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: beer-bom
          command: mvn install
          working_directory: beer-bom
      - store_artifacts:
          path: beer-bom/target
      - run:
          name: beer-service
          command: mvn install
          working_directory: beer-service
      - store_artifacts:
          path: beer-service/target
      - run:
          name: beer-inventory-service
          command: mvn install
          working_directory: beer-inventory-service
      - store_artifacts:
          path: beer-inventory-service/target
      - run:
          name: beer-order-service
          command: mvn install
          working_directory: beer-order-service
      - store_artifacts:
          path: beer-order-service/target
        
