version: '3.8'
services:

  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  eureka:
    image: neninho/brewery-eureka
    ports:
      - 8761:8761

  config:
    image: neninho/brewery-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"

  inventory-service:
    image: neninho/beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: localmysql, local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      #      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.102:3307/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_CONFIG_URI: http://config:8888
    restart: on-failure

  inventory-failover:
    image: neninho/brewery-inventory-failover
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: on-failure

  beer-service:
    image: neninho/beer-service
    ports:
      - 8080:8080
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: localmysql, local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      #      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.102:3307/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      BREWERY_BEER-INVENTORY-SERVICE-HOST: http://inventory-service:8082
    restart: on-failure

  order-service:
    image: neninho/beer-order-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_PROFILES_ACTIVE: localmysql, local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      #      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.0.102:3307/beerorderservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      BREWERY_BEER-SERVICE-HOST: http://beer-service:8080
    restart: on-failure

  gateway:
    image: neninho/brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - beer-service
      - inventory-service
      - order-service
      - inventory-failover
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:password@eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    restart: on-failure