package com.andrei.beer.order.service.domain;

public enum BeerOrderStatusEnum {
    NEW, VALIDATED, VALIDATION_PENDING, VALIDATION_EXCEPTION, ALLOCATED,
    ALLOCATION_PENDING, ALLOCATION_EXCEPTION, CANCELLED, PENDING_INVENTORY,
    PICKED_UP, DELIVERED, DELIVERY_EXCEPTION
}
